#!/bin/sh
#  ██████╗ ██╗ ██████╗███████╗    ██╗███╗   ██╗███████╗████████╗ █████╗ ██╗     ██╗     ███████╗██████╗
#  ██╔══██╗██║██╔════╝██╔════╝    ██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██║     ██║     ██╔════╝██╔══██╗
#  ██████╔╝██║██║     █████╗      ██║██╔██╗ ██║███████╗   ██║   ███████║██║     ██║     █████╗  ██████╔╝
#  ██╔══██╗██║██║     ██╔══╝      ██║██║╚██╗██║╚════██║   ██║   ██╔══██║██║     ██║     ██╔══╝  ██╔══██╗
#  ██║  ██║██║╚██████╗███████╗    ██║██║ ╚████║███████║   ██║   ██║  ██║███████╗███████╗███████╗██║  ██║
#  ╚═╝  ╚═╝╚═╝ ╚═════╝╚══════╝    ╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝╚═╝  ╚═╝
#
#	Author	-	gh0stzk
#	Repo	-	https://github.com/idxbhe/dotfiles
#	Last updated	-	24.03.2025 08:58:16
#
#	RiceInstaller - Script to install my dotfiles
#
# Copyright (C) 2021-2026 gh0stzk <z0mbi3.zk@protonmail.com>
# Licensed under GPL-3.0 license

# Colors
CRE=$(tput setaf 1)    # Red
CYE=$(tput setaf 3)    # Yellow
CGR=$(tput setaf 2)    # Green
CBL=$(tput setaf 4)    # Blue
BLD=$(tput bold)       # Bold
CNC=$(tput sgr0)       # Reset colors

# Logo
logo() {
    text="$1"
    printf "%b" "
               %%%
        %%%%%//%%%%%
      %%************%%%
  (%%//############*****%%
 %%%%**###&&&&&&&&&###**//
 %%(**##&&&#########&&&##**
 %%(**##*****#####*****##**%%%
 %%(**##     *****     ##**
   //##   @@**   @@   ##//
     ##     **###     ##
     #######     #####//
       ###**&&&&&**###
       &&&         &&&
       &&&////   &&
          &&//@@@**
            ..***

   ${BLD}${CRE}[ ${CYE}${text} ${CRE}]${CNC}\n\n"
}

initial_checks() {
    # Verificar usuario root
    if [ "$(id -u)" = 0 ]; then
        printf "This script MUST NOT be run as root user."
        exit 1
    fi

    # Verificar directorio HOME
    if [ "$PWD" != "$HOME" ]; then
        printf "The script must be executed from HOME directory."
        exit 1
    fi
}

welcome() {
    clear
    logo "Welcome $USER"

    printf "%b" "${BLD}${CGR}This script will install my dotfiles and this is what it will do:${CNC}

  ${BLD}${CGR}[${CYE}i${CGR}]${CNC} 2 Repositories will be installed. ${CBL}idxbhe-dotfiles${CNC} and ${CBL}Chaotic-Aur${CNC}
  ${BLD}${CGR}[${CYE}i${CGR}]${CNC} Check necessary dependencies and install them
  ${BLD}${CGR}[${CYE}i${CGR}]${CNC} Download my dotfiles in ${HOME}/dotfiles
  ${BLD}${CGR}[${CYE}i${CGR}]${CNC} Backup of possible existing configurations (bspwm, polybar, etc...)
  ${BLD}${CGR}[${CYE}i${CGR}]${CNC} Install my configuration
  ${BLD}${CGR}[${CYE}i${CGR}]${CNC} Enabling MPD service (Music player daemon)
  ${BLD}${CGR}[${CYE}i${CGR}]${CNC} Change your shell to zsh shell
  ${BLD}${CGR}[${CYE}i${CGR}]${CNC} Install SDDM and 7 SDDM themes (with selector)
  ${BLD}${CGR}[${CYE}i${CGR}]${CNC} Install GRUB theme (CyberGRUB-2077)

${BLD}${CGR}[${CRE}!${CGR}]${CNC} ${BLD}${CRE}My dotfiles DO NOT modify any of your system configurations${CNC}
${BLD}${CGR}[${CRE}!${CGR}]${CNC} ${BLD}${CRE}This script does NOT have the potential power to break your system${CNC}

"

    while :; do
        printf " %b" "${BLD}${CGR}Do you wish to continue?${CNC} [y/N]: "
        read -r yn
        case "$yn" in
            [Yy])
                break ;;
            [Nn]|"")
                printf "\n%b\n" "${BLD}${CYE}Operation cancelled${CNC}"
                exit 0 ;;
            *)
                printf "\n%b\n" "${BLD}${CRE}Error:${CNC} Just write '${BLD}${CYE}y${CNC}' or '${BLD}${CYE}n${CNC}'" ;;
        esac
    done
}

add_gh0stzk_repo() {
    clear
    logo "Add gh0stzk custom repo (for themes/icons packages)"
    repo_name="gh0stzk-dotfiles"
    sleep 2

    printf "%b\n" "${BLD}${CYE}Installing ${CBL}${repo_name}${CYE} repository...${CNC}"

    # Check if repository already exists in pacman.conf
    if ! pacman-conf --repo-list | grep -qx "$repo_name"; then
        printf "\n[%s]\nSigLevel = Optional TrustAll\nServer = http://gh0stzk.github.io/pkgs/x86_64\n" "$repo_name" \
           | sudo tee -a /etc/pacman.conf
        printf "\n%b\n" "${BLD}${CYE}${repo_name} ${CGR}repository added successfully!${CNC}"
        sleep 3
    else
        printf "\n%b\n" "${BLD}${CYE}The repository already exists and is configured${CNC}"
        sleep 3
    fi
}

add_chaotic_repo() {
    clear
    logo "Add chaotic-aur repository"
    repo_chaotic="chaotic-aur"
    key_id="3056513887B78AEB"
    sleep 2

    printf "%b\n" "${BLD}${CYE}Installing ${CBL}${repo_chaotic}${CYE} repository...${CNC}"

    # GPG key management
    if ! pacman-key -f "$key_id" >/dev/null 2>&1; then
        printf "%b\n" "${BLD}${CYE}Adding GPG key...${CNC}"
        sudo pacman-key --recv-key "$key_id" --keyserver keyserver.ubuntu.com

        printf "%b\n" "${BLD}${CYE}Signing key locally...${CNC}"
        sudo pacman-key --lsign-key "$key_id"
    else
        printf "\n%b\n" "${BLD}${CYE}GPG key already exists in keyring${CNC}"
    fi

    # Instalación de paquetes requeridos
    sudo pacman -U --noconfirm --needed 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst'
    sudo pacman -U --noconfirm --needed 'https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst'

    # Check if repository already exists in pacman.conf
    if ! pacman-conf --repo-list | grep -qx "$repo_chaotic"; then
        printf "\n%b\n" "${BLD}${CYE}Adding repository to pacman.conf...${CNC}"
        printf "\n[%s]\nInclude = /etc/pacman.d/chaotic-mirrorlist\n" "$repo_chaotic" \
            | sudo tee -a /etc/pacman.conf

        printf "%b\n" "\n${BLD}${CBL}${repo_chaotic} ${CGR}Repository configured successfully!${CNC}"
        sleep 3
    else
        printf "%b\n" "\n${BLD}${CYE}Repository already exists in pacman.conf${CNC}"
        sleep 3
    fi

}

install_dependencies() {
    clear
    logo "Installing needed packages from official repositories..."
    sleep 2

    sudo pacman -Syy
    dependencies="alacritty base-devel bat bc brightnessctl bspwm clipcat dunst eza feh fzf thunar tumbler gvfs-mtp firefox geany git grub imagemagick jq jgmenu kitty libwebp maim mpc mpd mpv neovim xcolor ncmpcpp npm pamixer pacman-contrib papirus-icon-theme picom playerctl polybar lxsession python-gobject redshift rofi rustup sddm sxhkd xclip xdg-user-dirs xdo xdotool xsettingsd xorg-xdpyinfo xorg-xkill xorg-xprop xorg-xrandr xorg-xsetroot xorg-xwininfo xorg-xrdb yazi zsh zsh-autosuggestions zsh-history-substring-search zsh-syntax-highlighting ttf-inconsolata ttf-jetbrains-mono ttf-jetbrains-mono-nerd ttf-terminus-nerd ttf-ubuntu-mono-nerd webp-pixbuf-loader noto-fonts noto-fonts-emoji"

    # Arrays temporales
    failed_deps=""
    retry_failed=""

    # First pass
    for pkg in $dependencies; do
        sleep 0.50
        if ! sudo pacman -S --noconfirm --needed "$pkg"; then
            failed_deps="$failed_deps $pkg"
        fi
    done

    # If there were failures, try again
    if [ -n "$failed_deps" ]; then
        printf "\n%b\n" "${BLD}${CRE}These dependencies failed:${CYE}${failed_deps}${CNC}"
        printf "%b\n\n" "${BLD}${CYE}Retrying installation..${CNC}"

        for pkg in $failed_deps; do
            sleep 0.50
            if ! sudo pacman -S --noconfirm --needed "$pkg"; then
                retry_failed="$retry_failed $pkg"
            fi
        done
    fi

    # Final Result
    if [ -n "$retry_failed" ]; then
        printf "\n%b\n" "${BLD}${CRE}These dependencies could not be installed after two attempts:${CYE}${retry_failed}${CNC}"
        printf "%b\n\n" "${BLD}${CBL}missing_apps.txt ${CYE}file was created on your ${CGR}HOME ${CYE}with the list."
        printf "The following dependencies failed, please install manually:\n%s\n" "$retry_failed" > missing_apps.txt
    else
        if [ -z "$failed_deps" ]; then
            printf "\n%b\n" "${BLD}${CGR}All dependencies were installed successfully.${CNC}"
        else
            printf "\n%b\n" "${BLD}${CGR}All dependencies were installed successfully after retry${CNC}"
        fi
    fi
    sleep 3
}

install_gh0stzk_dependencies() {
    clear
    logo "Installing needed packages from gh0stzk repository..."
    sleep 2

    gh0stzk_dependencies="st-gh0stzk gh0stzk-gtk-themes gh0stzk-cursor-qogirr gh0stzk-icons-beautyline gh0stzk-icons-candy gh0stzk-icons-catppuccin-mocha gh0stzk-icons-dracula gh0stzk-icons-glassy gh0stzk-icons-gruvbox-plus-dark gh0stzk-icons-hack gh0stzk-icons-luv gh0stzk-icons-sweet-rainbow gh0stzk-icons-tokyo-night gh0stzk-icons-vimix-white gh0stzk-icons-zafiro gh0stzk-icons-zafiro-purple"

    # Arrays temporales
    failed_gh0st_deps=""
    retry_gh0st_failed=""

    # First pass
    for gh0stzk_pkg in $gh0stzk_dependencies; do
        sleep 0.50
        if ! sudo pacman -S --noconfirm --needed "$gh0stzk_pkg"; then
            failed_gh0st_deps="$failed_gh0st_deps $gh0stzk_pkg"
        fi
    done

    # If there were failures, try again
    if [ -n "$failed_gh0st_deps" ]; then
        printf "\n%b\n" "${BLD}${CRE}These dependencies failed:${CYE}${failed_gh0st_deps}${CNC}"
        printf "%b\n\n" "${BLD}${CYE}Retrying installation..${CNC}"

        for gh0stzk_pkg in $failed_gh0st_deps; do
            sleep 0.50
            if ! sudo pacman -S --noconfirm --needed "$gh0stzk_pkg"; then
                retry_gh0st_failed="$retry_gh0st_failed $gh0stzk_pkg"
            fi
        done
    fi

    # Final Result
    if [ -n "$retry_gh0st_failed" ]; then
        printf "\n%b\n" "${BLD}${CRE}These dependencies could not be installed after two attempts:${CYE}${retry_gh0st_failed}${CNC}"
        printf "%b\n\n" "${BLD}${CBL}missing_apps.txt ${CYE}file was created on your ${CGR}HOME ${CYE}with the list."
        printf "\nApps from gh0stzk repo\n=======================\nInstall with pacman command.\nThe following dependencies failed, please install manually:\n%s\n" "$retry_gh0st_failed" >> missing_apps.txt
    else
        if [ -z "$failed_gh0st_deps" ]; then
            printf "\n%b\n" "${BLD}${CGR}All dependencies were installed successfully.${CNC}"
        else
            printf "\n%b\n" "${BLD}${CGR}All dependencies were installed successfully after retry${CNC}"
        fi
    fi

    sleep 3
}

install_chaotic_dependencies() {
    clear
    logo "Installing needed packages from chaotic repository..."
    sleep 2

    chaotic_dependencies="i3lock-color simple-mtpfs fzf-tab-git paru-git eww-git"

    # Arrays temporales
    failed_chaotic_deps=""
    retry_chaotic_failed=""

    # First pass
    for chaotic_pkg in $chaotic_dependencies; do
        sleep 0.50
        if ! sudo pacman -S --noconfirm --needed "$chaotic_pkg"; then
            failed_chaotic_deps="$failed_chaotic_deps $chaotic_pkg"
        fi
    done

    # If there were failures, try again
    if [ -n "$failed_chaotic_deps" ]; then
        printf "\n%b\n" "${BLD}${CRE}These dependencies failed:${CYE}${failed_chaotic_deps}${CNC}"
        printf "%b\n\n" "${BLD}${CYE}Retrying installation..${CNC}"

        for chaotic_pkg in $failed_chaotic_deps; do
            sleep 0.50
            if ! sudo pacman -S --noconfirm --needed "$chaotic_pkg"; then
                retry_chaotic_failed="$retry_chaotic_failed $chaotic_pkg"
            fi
        done
    fi

    # Final Result
    if [ -n "$retry_chaotic_failed" ]; then
        printf "\n%b\n" "${BLD}${CRE}These dependencies could not be installed after two attempts:${CYE}${retry_chaotic_failed}${CNC}"
        printf "%b\n\n" "${BLD}${CBL}missing_apps.txt ${CYE}file was created on your ${CGR}HOME ${CYE}with the list."
        printf "\nApps from Chaotic\n=======================\nInstall with pacman command.\nThe following dependencies failed, please install manually:\n%s\n" "$retry_chaotic_failed" >> missing_apps.txt
    else
        if [ -z "$failed_chaotic_deps" ]; then
            printf "\n%b\n" "${BLD}${CGR}All dependencies were installed successfully.${CNC}"
        else
            printf "\n%b\n" "${BLD}${CGR}All dependencies were installed successfully after retry${CNC}"
        fi
    fi
    sleep 3
}

install_aur_dependencies() {
    clear
    logo "Installing AUR dependencies..."
    sleep 2

    if ! command -v paru >/dev/null 2>&1; then
        printf "%b\n" "${BLD}${CYE}Installing PARU${CNC}"
        git clone https://aur.archlinux.org/paru.git
        cd paru
        makepkg -si
        cd
    fi

    aur_dependencies="xwinwrap-0.9-bin shiki-bin"

    # Arrays temporales
    failed_aur_deps=""
    retry_aur_failed=""

    # First pass
    for aur_pkg in $aur_dependencies; do
        sleep 0.50
        if ! paru -S --skipreview --noconfirm "$aur_pkg"; then
            failed_aur_deps="$failed_aur_deps $aur_pkg"
        fi
    done

    # If there were failures, try again
    if [ -n "$failed_aur_deps" ]; then
        printf "\n%b\n" "${BLD}${CRE}These dependencies failed:${CYE}${failed_aur_deps}${CNC}"
        printf "%b\n\n" "${BLD}${CYE}Retrying installation..${CNC}"

        for aur_pkg in $failed_aur_deps; do
            sleep 0.50
            if ! paru -S --skipreview --noconfirm "$aur_pkg"; then
                retry_aur_failed="$retry_aur_failed $aur_pkg"
            fi
        done
    fi

    # Final Result
    if [ -n "$retry_aur_failed" ]; then
        printf "\n%b\n" "${BLD}${CRE}These dependencies could not be installed after two attempts:${CYE}${retry_aur_failed}${CNC}"
        printf "%b\n\n" "${BLD}${CBL}missing_apps.txt ${CYE}file was created on your ${CGR}HOME ${CYE}with the list."
        printf "\nApps from AUR\n=======================\nInstall with paru command.\nThe following dependencies failed, please install manually:\n%s\n" "$retry_aur_failed" >> missing_apps.txt
    else
        if [ -z "$failed_aur_deps" ]; then
            printf "\n%b\n" "${BLD}${CGR}All dependencies were installed successfully.${CNC}"
        else
            printf "\n%b\n" "${BLD}${CGR}All dependencies were installed successfully after retry${CNC}"
        fi
    fi
    sleep 3
}

clone_dotfiles() {
    clear
    logo "Downloading dotfiles"
    repo_url="https://github.com/idxbhe/dotfiles"
    repo_dir="$HOME/.local/share/idxbhe"
    timestamp=$(date +"%Y%m%d-%H%M%S")
    sleep 2

    # Handle existing repository
    if [ -d "$repo_dir" ]; then
        backup_dir="${repo_dir}_$timestamp"
        printf "%b\n" "${BLD}${CYE}Existing repository found - renaming to: ${CBL}${backup_dir}${CNC}"

        mv -v "$repo_dir" "$backup_dir"
    fi

    # Clone new repository
    printf "%b\n" "${BLD}${CYE}Cloning dotfiles from: ${CBL}${repo_url}${CNC}"
    git clone --depth=1 "$repo_url" "$repo_dir"
    sleep 3
}

backup_existing_config() {
    clear
    logo "Backup files"
    sleep 2

    printf "%b" "My dotfiles come with a lightweight, simple, and functional Neovim configuration.\nBut if you already have a custom, super pro Neovim configuration and don't want to try mine, just type 'n'\n"

    while :; do
        printf "%b" "${BLD}${CYE}Do you want to use my Neovim setup? ${CNC}[y/N]: "
        read -r try_nvim
        case "$try_nvim" in
            [Yy]) try_nvim="y"; break ;;
            [Nn]) try_nvim="n"; break ;;
            *) printf " %b%bError:%b write 'y' or 'n'\n" "${BLD}" "${CRE}" "${CNC}" ;;
        esac
    done

    printf "\nMy dotfiles come with a beautiful, minimalist Firefox theme, but if you don't want to try it, just type 'n'.\n"

     while :; do
        printf "%b" "${BLD}${CYE}Do you want to use my Firefox theme? ${CNC}[y/N]: "
        read -r try_firefox
        case "$try_firefox" in
            [Yy]) try_firefox="y"; break ;;
            [Nn]) try_firefox="n"; break ;;
            *) printf " %b%bError:%b write 'y' or 'n'\n" "${BLD}" "${CRE}" "${CNC}" ;;
        esac
    done

    backup_folder="$HOME/.RiceBackup/$(date +%Y%m%d-%H%M%S)"
    mkdir -p "$backup_folder"
    printf "\n%b\n\n" "${BLD}${CYE}Backup directory: ${CBL}$backup_folder${CNC}"
    sleep 1

    # Dirs in ~/.config/
    cfg_dir="bspwm alacritty cava clipcat ghostty picom rofi eww sxhkd dunst jgmenu kitty polybar geany gtk-3.0 ncmpcpp yazi zsh mpd mpv paru st zathura"
    for cfg in $cfg_dir; do
        [ -d "$HOME/.config/$cfg" ] && mv "$HOME/.config/$cfg" "$backup_folder"
    done

    # Individual files/dirs in Home
    for f in ".icons" ".zshrc" ".gtkrc-2.0"; do
        [ -e "$HOME/$f" ] && mv "$HOME/$f" "$backup_folder"
    done

    # If ppl wanna try my nvim config
    if [ "$try_nvim" = "y" ]; then
        [ -d "$HOME/.config/nvim" ] && mv "$HOME/.config/nvim" "$backup_folder"
    fi

    # If ppl wanna try my firefox config
    if [ "$try_firefox" = "y" ]; then
        # Create a Firefox profile if none exists
        if [ ! -d "$HOME/.mozilla" ] && [ ! -d "$HOME/.config/mozilla" ]; then
            printf "%b\n" "${BLD}${CYE}Creating Firefox profile...${CNC}"
            timeout 1s firefox --headless --display=0 >/dev/null 2>&1
            sleep 1
        fi

        firefox_profile=$(
            find "$HOME/.config/mozilla/firefox" "$HOME/.mozilla/firefox" \
                -maxdepth 1 -type d -name '*.default-release' 2>/dev/null | head -n 1)

        if [ -n "$firefox_profile" ]; then
            [ -d "$firefox_profile/chrome" ] && mv "$firefox_profile/chrome" "$backup_folder"
            [ -f "$firefox_profile/user.js" ] && mv "$firefox_profile/user.js" "$backup_folder"
        fi
    fi

    printf "\n%b\n\n" "${BLD}${CGR}All files moved to:${CNC} ${BLD}${CYE}$backup_folder${CNC}"
    sleep 3
}

install_dotfiles() {
    clear
    logo "Installing dotfiles.."
    printf "%s%s Copying files to respective directories...%s\n\n" "$BLD" "$CBL" "$CNC"
    sleep 2

    # Create required directories if not exists
    for dir in "$HOME/.config" "$HOME/.local/bin" "$HOME/.local/share"; do
        if [ ! -d "$dir" ]; then
            mkdir -p "$dir" && \
            printf "%s%sCreated directory: %s%s%s\n" "$BLD" "$CGR" "$CBL" "$dir" "$CNC"
        fi
    done

    # Copy files to ~/.config
    dots_config_dir="alacritty bspwm cava clipcat dunst geany ghostty gtk-3.0 jgmenu kitty mpd mpv ncmpcpp paru systemd yazi zsh st zathura"
    for dots_cfg in $dots_config_dir; do
        cp -R "$HOME/.local/share/idxbhe/config/$dots_cfg" "$HOME/.config/"
    done

    # If ppl wanna try my nvim config
    [ "$try_nvim" = "y" ] && cp -R "$HOME/.local/share/idxbhe/config/nvim" "$HOME/.config/"

    # If ppl wanna try my firefox config
    if [ "$try_firefox" = "y" ]; then
        firefox_profile=$(
            find "$HOME/.config/mozilla/firefox" "$HOME/.mozilla/firefox" \
                -maxdepth 1 -type d -name '*.default-release' 2>/dev/null | head -n 1)

        if [ -n "$firefox_profile" ]; then
            cp -R "$HOME/.local/share/idxbhe/misc/firefox/chrome" "$firefox_profile"
            cp "$HOME/.local/share/idxbhe/misc/firefox/user.js" "$firefox_profile"

            [ -f "$firefox_profile/user.js" ] && sed -i "s|/home/z0mbi3|/home/$USER|g" "$firefox_profile/user.js"
        fi

        # Copy startup-page
        cp -R "$HOME/.local/share/idxbhe/misc/startup-page" "$HOME/.local/share/"

        timezone=$(timedatectl show --property=Timezone --value 2>/dev/null)
        [ -z "$timezone" ] && timezone=$(readlink /etc/localtime 2>/dev/null | sed 's|.*/zoneinfo/||')

        sed -i \
            -e "0,/^[[:space:]]*name:/s|'.*'|'$USER'|" \
            -e "/^[[:space:]]*timeZone:/s|'.*'|'$timezone'|" \
        "$HOME/.local/share/startup-page/config.js"
    fi

    # Copy files to ~/.local/share
    dots_misc_dir="applications asciiart fonts"
    for dots_misc in $dots_misc_dir; do
        cp -R "$HOME/.local/share/idxbhe/misc/$dots_misc" "$HOME/.local/share/"
    done

    # Copy bin dir to ~/.local
    cp -R "$HOME/.local/share/idxbhe/misc/bin" "$HOME/.local/"


    # Copy remaining files
    dots_home_dir=".icons .zshrc .gtkrc-2.0"
    for dots_home in $dots_home_dir; do
        cp -R "$HOME/.local/share/idxbhe/home/$dots_home" "$HOME/"
    done

    # Copying polybar-update.hook
    if [ ! -d /etc/pacman.d/hooks ]; then
        sudo mkdir -p /etc/pacman.d/hooks
    fi

    sudo cp "$HOME/.local/share/idxbhe/misc/polybar-update.hook" /etc/pacman.d/hooks

    # Update font cache
    fc-cache -r

    # Generate xdg dirs
    if [ ! -e "$HOME/.config/user-dirs.dirs" ]; then
        xdg-user-dirs-update
    fi

    printf "\n%s%sDotfiles installed successfully!%s\n" "$BLD" "$CGR" "$CNC"
    sleep 3
}

install_sddm_themes() {
    clear
    logo "Installing SDDM themes.."
    printf "%s%s Deploying SDDM themes to local + system directories...%s\n\n" "$BLD" "$CBL" "$CNC"
    sleep 2

    local SRC="$HOME/.local/share/idxbhe/sddm/themes"
    local LOCAL_DEST="$HOME/.config/bspwm/sddm-themes"
    local SYSTEM_DEST="/usr/share/sddm/themes"

    # Bail early if source missing
    if [ ! -d "$SRC" ]; then
        printf "%b\n" "${BLD}${CRE}SDDM themes source not found: ${CYE}${SRC}${CNC}"
        printf "%b\n" "${BLD}${CYE}Skipping SDDM theme installation.${CNC}"
        sleep 3
        return 0
    fi

    # 1) Copy to local user container (~/.config/bspwm/sddm-themes/)
    #    Acts as the permanent repo that SddmSelector reads from,
    #    so users keep their themes after deleting ~/.local/share/idxbhe
    mkdir -p "$LOCAL_DEST"
    if cp -R "$SRC/." "$LOCAL_DEST/"; then
        printf "%b\n" "${BLD}${CGR}✔ Copied themes to ${CBL}${LOCAL_DEST}${CGR} (local user container)${CNC}"
    else
        printf "%b\n" "${BLD}${CRE}✘ Failed to copy themes to ${CYE}${LOCAL_DEST}${CNC}"
    fi

    # 2) Copy to system location (/usr/share/sddm/themes/)
    if [ "$(id -u)" -eq 0 ]; then
        printf "%b\n" "${BLD}${CRE}Running as root, skipping sudo for system copy${CNC}"
        SUDO_CMD=""
    else
        SUDO_CMD="sudo"
    fi

    if [ ! -d "$SYSTEM_DEST" ]; then
        $SUDO_CMD mkdir -p "$SYSTEM_DEST"
    fi

    local copy_failed=""
    for theme_dir in "$SRC"/*/; do
        [ -d "$theme_dir" ] || continue
        local theme_name
        theme_name="$(basename "$theme_dir")"

        if $SUDO_CMD rm -rf "$SYSTEM_DEST/$theme_name" 2>/dev/null \
           && $SUDO_CMD cp -R "$theme_dir" "$SYSTEM_DEST/$theme_name"; then
            printf "%b\n" "${BLD}${CGR}  ✔ Installed system theme: ${CBL}${theme_name}${CNC}"
        else
            copy_failed="$copy_failed $theme_name"
            printf "%b\n" "${BLD}${CRE}  ✘ Failed system install: ${CYE}${theme_name}${CNC}"
        fi
    done

    if [ -n "$copy_failed" ]; then
        printf "\n%b\n" "${BLD}${CRE}Failed system copies:${CYE}${copy_failed}${CNC}"
    fi

    # 3) Generate /etc/sddm.conf.d/theme.conf with first theme as default
    #    (user can change later via SddmSelector / Super+R -> SDDM tab)
    if $SUDO_CMD mkdir -p "/etc/sddm.conf.d"; then
        local first_theme
        first_theme="$(ls -1 "$SRC" 2>/dev/null | head -n 1)"
        if [ -n "$first_theme" ]; then
            if [ ! -f "/etc/sddm.conf.d/theme.conf" ]; then
                printf "[Theme]\nCurrent=%s\n" "$first_theme" | $SUDO_CMD tee "/etc/sddm.conf.d/theme.conf" >/dev/null
                printf "%b\n" "${BLD}${CGR}✔ Set default SDDM theme: ${CBL}${first_theme}${CNC}"
            else
                $SUDO_CMD sed -i "s|^Current=.*|Current=$first_theme|" "/etc/sddm.conf.d/theme.conf" 2>/dev/null
                printf "%b\n" "${BLD}${CGR}✔ Updated default SDDM theme: ${CBL}${first_theme}${CNC}"
            fi
        fi
    fi

    # 4) Copy sddm.sh helper next to SddmSelector for manual use later
    if [ -f "$HOME/.local/share/idxbhe/sddm/sddm.sh" ]; then
        mkdir -p "$HOME/.local/bin"
        cp "$HOME/.local/share/idxbhe/sddm/sddm.sh" "$HOME/.local/bin/sddm-install.sh"
        chmod +x "$HOME/.local/bin/sddm-install.sh"
        printf "%b\n" "${BLD}${CGR}✔ Helper installed: ${CBL}~/.local/bin/sddm-install.sh${CNC}"
    fi

    printf "\n%s%sSDDM themes installation complete!%s\n" "$BLD" "$CGR" "$CNC"
    sleep 3
}

install_grub_theme() {
    clear
    logo "Installing GRUB theme (CyberGRUB-2077).."
    printf "%s%s Deploying GRUB theme to system...%s\n\n" "$BLD" "$CBL" "$CNC"
    sleep 2

    local SRC="$HOME/.local/share/idxbhe/grub/CyberGRUB-2077"
    local THEME_NAME="CyberGRUB-2077"
    local THEME_DIR=""
    local GRUB_ALIAS="grub"
    local GRUB_COMMAND="grub-mkconfig"

    # Bail early if source missing
    if [ ! -d "$SRC" ]; then
        printf "%b\n" "${BLD}${CRE}GRUB theme source not found: ${CYE}${SRC}${CNC}"
        printf "%b\n" "${BLD}${CYE}Skipping GRUB theme installation.${CNC}"
        sleep 3
        return 0
    fi

    # Detect grub vs grub2
    if command -v grub2-mkconfig >/dev/null 2>&1 && [ -d "/boot/grub2" ]; then
        GRUB_ALIAS="grub2"
        GRUB_COMMAND="grub2-mkconfig"
        THEME_DIR="/boot/grub2/themes"
    elif command -v grub-mkconfig >/dev/null 2>&1 && [ -d "/boot/grub" ]; then
        GRUB_ALIAS="grub"
        GRUB_COMMAND="grub-mkconfig"
        THEME_DIR="/boot/grub/themes"
    else
        printf "%b\n" "${BLD}${CRE}No GRUB installation detected (no grub-mkconfig or grub2-mkconfig).${CNC}"
        printf "%b\n" "${BLD}${CYE}Skipping GRUB theme installation.${CNC}"
        sleep 3
        return 0
    fi

    printf "%b\n" "${BLD}${CYE}Detected: ${CBL}${GRUB_ALIAS}${CYE} (${GRUB_COMMAND})${CNC}"

    # Create theme directory if needed
    if [ ! -d "$THEME_DIR" ]; then
        sudo mkdir -p "$THEME_DIR"
        printf "%b\n" "${BLD}${CYE}Created ${THEME_DIR}${CNC}"
    fi

    # Copy theme to system
    if sudo rm -rf "${THEME_DIR}/${THEME_NAME}" 2>/dev/null \
       && sudo cp -R "$SRC" "${THEME_DIR}/"; then
        printf "%b\n" "${BLD}${CGR}✔ Installed GRUB theme: ${CBL}${THEME_NAME}${CNC} to ${THEME_DIR}/${THEME_NAME}"
    else
        printf "%b\n" "${BLD}${CRE}✘ Failed to copy GRUB theme to ${THEME_DIR}${CNC}"
        sleep 3
        return 1
    fi

    # Update /etc/default/grub
    local GRUB_CFG="/etc/default/grub"
    local GRUB_THEME_PATH="GRUB_THEME=\"${THEME_DIR}/${THEME_NAME}/theme.txt\""

    if [ ! -f "$GRUB_CFG" ]; then
        printf "%b\n" "${BLD}${CRE}GRUB config not found: ${CYE}${GRUB_CFG}${CNC}"
        sleep 3
        return 1
    fi

    # Backup original
    sudo cp "$GRUB_CFG" "${GRUB_CFG}.backup.$(date +%Y%m%d-%H%M%S)"

    # Update GRUB_THEME
    if grep -qE '^#?GRUB_THEME=' "$GRUB_CFG"; then
        sudo sed -i -E "s|^#?GRUB_THEME=.*|${GRUB_THEME_PATH}|" "$GRUB_CFG"
    else
        echo "" | sudo tee -a "$GRUB_CFG" >/dev/null
        echo "$GRUB_THEME_PATH" | sudo tee -a "$GRUB_CFG" >/dev/null
    fi

    # Disable terminal output (required for graphical theme)
    sudo sed -i 's/^GRUB_TERMINAL_OUTPUT=/#GRUB_TERMINAL_OUTPUT=/' "$GRUB_CFG"

    # Set GFXMODE to auto
    if grep -qE '^#?GRUB_GFXMODE=' "$GRUB_CFG"; then
        sudo sed -i -E 's|^#?GRUB_GFXMODE=.*|GRUB_GFXMODE=auto|' "$GRUB_CFG"
    else
        echo "GRUB_GFXMODE=auto" | sudo tee -a "$GRUB_CFG" >/dev/null
    fi
    sudo sed -i 's/^#GRUB_GFXMODE=/GRUB_GFXMODE=/' "$GRUB_CFG"

    # Set GFXPAYLOAD_LINUX to keep
    if grep -qE '^#?GRUB_GFXPAYLOAD_LINUX=' "$GRUB_CFG"; then
        sudo sed -i -E 's|^#?GRUB_GFXPAYLOAD_LINUX=.*|GRUB_GFXPAYLOAD_LINUX=keep|' "$GRUB_CFG"
    else
        echo "GRUB_GFXPAYLOAD_LINUX=keep" | sudo tee -a "$GRUB_CFG" >/dev/null
    fi
    sudo sed -i 's/^#GRUB_GFXPAYLOAD_LINUX=/GRUB_GFXPAYLOAD_LINUX=/' "$GRUB_CFG"

    printf "%b\n" "${BLD}${CGR}✔ Updated ${GRUB_CFG} with theme settings${CNC}"

    # Regenerate grub.cfg
    local GRUB_CONFIG_PATH="/boot/${GRUB_ALIAS}/grub.cfg"
    printf "%b\n" "${BLD}${CYE}Regenerating ${GRUB_CONFIG_PATH}...${CNC}"

    if sudo "${GRUB_COMMAND}" -o "${GRUB_CONFIG_PATH}" >/dev/null 2>&1; then
        printf "%b\n" "${BLD}${CGR}✔ GRUB config regenerated: ${GRUB_CONFIG_PATH}${CNC}"
    else
        printf "%b\n" "${BLD}${CRE}✘ Failed to regenerate GRUB config${CNC}"
        sleep 3
        return 1
    fi

    # Copy helper script for manual use later
    if [ -f "$HOME/.local/share/idxbhe/grub/install.sh" ]; then
        cp "$HOME/.local/share/idxbhe/grub/install.sh" "$HOME/.local/bin/grub-theme-install.sh"
        chmod +x "$HOME/.local/bin/grub-theme-install.sh"
        printf "%b\n" "${BLD}${CGR}✔ Helper installed: ${CBL}~/.local/bin/grub-theme-install.sh${CNC}"
    fi

    printf "\n%s%sGRUB theme installation complete!%s\n" "$BLD" "$CGR" "$CNC"
    sleep 3
}

configure_services() {
    clear
    logo "Configuring Services"
    picom_config="$HOME/.config/bspwm/config/picom/picom.conf"
    sleep 2

    # MPD Service Management
    if systemctl is-enabled --quiet mpd.service; then
        printf "%b\n" "${BLD}${CYE}Disabling global MPD service...${CNC}"
        sudo systemctl disable --now mpd.service
    fi

    # User-level MPD Service
    printf "%b\n" "${BLD}${CYE}Enabling user MPD service...${CNC}"
    systemctl --user enable --now mpd.service

    # User-level ArchUpdates
    printf "%b\n" "${BLD}${CYE}Enabling user ArchUpdates service...${CNC}"
    systemctl --user enable --now ArchUpdates.timer

    # SDDM Display Manager
    # Only enable if SDDM binary is actually present (avoids breaking headless installs)
    if command -v sddm >/dev/null 2>&1; then
        # Disable any other installed display manager first (gdm, lightdm, lxdm, ly)
        for dm in gdm lightdm lxdm ly; do
            if systemctl list-unit-files "${dm}.service" 2>/dev/null | grep -q "${dm}.service"; then
                if systemctl is-enabled --quiet "${dm}.service" 2>/dev/null; then
                    printf "%b\n" "${BLD}${CYE}Disabling conflicting DM: ${CBL}${dm}${CNC}"
                    sudo systemctl disable --now "${dm}.service" 2>/dev/null || true
                fi
            fi
        done

        # Enable SDDM (system service, not --user)
        printf "%b\n" "${BLD}${CYE}Enabling SDDM display manager...${CNC}"
        if sudo systemctl enable sddm.service 2>/dev/null; then
            printf "%b\n" "${BLD}${CGR}SDDM service enabled successfully${CNC}"
        else
            printf "%b\n" "${BLD}${CRE}Failed to enable SDDM service (continuing anyway)${CNC}"
        fi
    else
        printf "%b\n" "${BLD}${CYE}SDDM not installed, skipping service enable${CNC}"
    fi

    # Virtual Machine Detection
    is_virtual_machine() {
        systemd-detect-virt --quiet >/dev/null 2>&1
    }

    # Picom Configuration for VMs
    if is_virtual_machine; then
        printf "%b\n" "${BLD}${CYE}Virtual machine detected${CNC}"
        printf "\n%b\n" "${BLD}${CYE}Adjusting Picom configuration...${CNC}"

        if [ -f "$picom_config" ]; then
            if sed -i 's/backend = "glx"/backend = "xrender"/' "$picom_config"; then
                printf "%b\n" "${BLD}${CGR}Picom backend changed to xrender${CNC}"
            else
                printf "%b\n" "${BLD}${CRE}Failed to adjust Picom settings${CNC}"
            fi
        else
            printf "%b\n\n" "${BLD}${CRE}Picom config file missing: ${CYE}${picom_config}${CNC}"
        fi

        if [ -f "$picom_config" ]; then
            if sed -i 's/vsync = true/vsync = false/' "$picom_config"; then
                printf "%b\n\n" "${BLD}${CGR}Picom vSync disabled${CNC}"
            else
                printf "%b\n\n" "${BLD}${CRE}Failed to adjust Picom settings${CNC}"
            fi
        else
            printf "%b\n\n" "${BLD}${CRE}Picom config file missing: ${CYE}${picom_config}${CNC}"
        fi
    fi
    sleep 3
}

change_default_shell() {
    clear
    logo "Changing default shell to zsh"
    zsh_path=$(command -v zsh)
    sleep 2

    if [ -z "$zsh_path" ]; then
        printf "%b\n\n" "${BLD}${CRE}Zsh is not installed! Cannot change shell${CNC}"
    fi

    if [ "$SHELL" != "$zsh_path" ]; then
        printf "%b\n" "${BLD}${CYE}Changing your shell to Zsh...${CNC}"

        if chsh -s "$zsh_path"; then
            printf "%b\n" "\n${BLD}${CGR}Shell changed successfully!${CNC}"
        else
            printf "%b\n\n" "\n${BLD}${CRE}Error changing shell!{CNC}"
        fi
    else
        printf "%b\n\n" "${BLD}${CGR}Zsh is already your default shell!${CNC}"
    fi
    sleep 3
}

final_prompt() {
    clear
    logo "Installation Complete"

    printf "%b\n" "${BLD}${CGR}Installation completed successfully!${CNC}"
    printf "%b\n\n" "${BLD}${CRE}You ${CBL}MUST ${CRE}restart your system to apply changes${CNC}"

    while :; do
        printf "%b" "${BLD}${CYE}Reboot now?${CNC} [y/N]: "
        read -r yn
        case "$yn" in
            [Yy]) printf "\n%b\n" "${BLD}${CGR}Initiating reboot...${CNC}"
                sleep 1
                sudo reboot
                break ;;
            [Nn]|"") printf "\n%b\n\n" "${BLD}${CYE}You really need to reboot bro!!${CNC}"
                    break ;;
            *) printf " %b%bError:%b write 'y' or 'n'\n" "${BLD}" "${CRE}" "${CNC}" ;;
        esac
    done
}

# --- Main run --- #
initial_checks
welcome
add_gh0stzk_repo
add_chaotic_repo

install_dependencies
install_gh0stzk_dependencies
install_chaotic_dependencies
install_aur_dependencies

clone_dotfiles

backup_existing_config
install_dotfiles
install_sddm_themes
install_grub_theme
configure_services
change_default_shell
final_prompt
